version: '3.8'
 
services:
    reservaciones:
        build: 
            context: .
            args:
                - APP_ENV=${APP_ENV}
                - APP_SECRET=${APP_SECRET}
                - DATABASE_URL=${DATABASE_URL}
        ports:
            - 8080:80
